name: Docker Build and Push

on:
  push:
    branches: [ "development" ]
    paths:
      - ".github/workflows/build-docs.yml"
      - "Dockerfile"
      - "docs/**"
      - "docs-resources/**"
      - "mkdocs.yml"
      - "pyproject.toml"
      - "poetry.lock"

jobs:
  build:
    runs-on: ubuntu-latest
    if: vars.DO_BUILD_DOCS == 'true'
    permissions:
      contents: read
      packages: write    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ secrets.REGISTRY_URL }}/clangen/clangen-docs
          tags: |
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}
      - name: Login to private registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          secrets: |
            mkdocs_git_committers_apikey=${{ secrets.GITHUB_TOKEN }}
      - name: Set up kubernetex context
        uses: azure/setup-kubectl@v3
      - name: Set Kubernetes context
        uses: Azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.DOCS_RESTART_KUBECONFIG }}
      - name: Restart deployment
        run: kubectl rollout restart deployment/clangen-docs -n clangen
